apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: post-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          value: "supppppersecretkeyimxD"
