apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
  labels:
    app: team-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
      - name: team-service
        image: team-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: teamservice
        - name: DB_PORT
          value: "5432"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /teams
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /teams
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5 