apiVersion: v1
kind: Service
metadata:
  name: team-service
spec:
  selector:
    app: team-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31082
  type: NodePort 