apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
  labels:
    app: team-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
      - name: team-service
        image: team-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
        - name: JWT_SECRET
          value: "supppppersecretkeyimxD"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: "teamservice"
        - name: PORT
          value: "8084" 